/* ==========================================================================
   PRODUCTS CATALOG — Dakar Dapper
   ========================================================================== */
const PRODUCTS = [
  {
    id: 1,
    name: "Lavender Double-Breasted Blazer",
    subtitle: "Premium Italian Wool Blend",
    category: "wears",
    price: 185000,
    originalPrice: 225000,
    image: "assets/blazer.jpg",
    badge: "Bestseller",
    badgeType: "tag-dark",
    isNew: true,
    colors: ["#C8A2C8", "#1A1A2E", "#3C3C3C"],
    colorNames: ["Lavender", "Navy", "Charcoal"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.9,
    reviews: 47,
    description: "Our signature double-breasted blazer crafted from premium Italian wool blend. Features gold-tone buttons, notch lapels, and a tailored silhouette that transitions effortlessly from boardroom to evening events.",
    details: ["100% Italian wool blend", "Gold-tone metal buttons", "Notch lapel, double-breasted closure", "Fully lined interior", "Two patch pockets", "Dry clean only"],
    care: "Dry clean only. Store on a padded hanger. Steam to remove wrinkles."
  },
  {
    id: 2,
    name: "Charcoal Utility Overshirt",
    subtitle: "Heavyweight Cotton Twill",
    category: "wears",
    price: 72000,
    originalPrice: null,
    image: "assets/overshirt.jpg",
    badge: "New",
    badgeType: "tag-gold",
    isNew: true,
    colors: ["#2C2C2C", "#4A5043", "#5C4B3A"],
    colorNames: ["Charcoal", "Olive", "Tobacco"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.7,
    reviews: 23,
    description: "A versatile utility overshirt in heavyweight cotton twill. Designed with dual chest flap pockets and a relaxed modern fit, perfect as a layering piece or standalone jacket.",
    details: ["100% heavyweight cotton twill", "Dual flap chest pockets", "Button-front closure", "Relaxed fit", "Interior welt pocket", "Machine wash cold"],
    care: "Machine wash cold, tumble dry low. Iron on medium heat if needed."
  },
  {
    id: 3,
    name: "Oversized Washed Hoodie",
    subtitle: "Garment-Dyed French Terry",
    category: "wears",
    price: 48000,
    originalPrice: 62000,
    image: "assets/hoodie.jpg",
    badge: null,
    badgeType: null,
    isNew: false,
    colors: ["#1C1C1C", "#5B5B5B", "#E8E4DF"],
    colorNames: ["Washed Black", "Storm Grey", "Bone"],
    sizes: ["M", "L", "XL", "XXL"],
    rating: 4.8,
    reviews: 89,
    description: "Premium oversized hoodie in garment-dyed French terry cotton. Features a heavy weight, kangaroo pocket, and a vintage washed finish for an effortlessly cool aesthetic.",
    details: ["450gsm garment-dyed French terry", "Oversized relaxed fit", "Kangaroo front pocket", "Drawcord hood", "Ribbed cuffs and hem", "Machine wash cold"],
    care: "Machine wash cold inside-out. Hang dry for best results."
  },
  {
    id: 4,
    name: "Chronograph Rose Gold Watch",
    subtitle: "Automatic Movement, Leather Strap",
    category: "accessories",
    price: 320000,
    originalPrice: null,
    image: "assets/watch.jpg",
    badge: "Limited",
    badgeType: "tag-dark",
    isNew: true,
    colors: ["#8B6914", "#C0C0C0", "#1A1A1A"],
    colorNames: ["Rose Gold", "Silver", "Noir"],
    sizes: ["One Size"],
    rating: 5.0,
    reviews: 12,
    description: "A stunning automatic chronograph timepiece featuring a rose gold case, dark sunray dial with three sub-dials, and a genuine alligator leather strap. Swiss-inspired movement with 42-hour power reserve.",
    details: ["Rose gold-plated stainless steel case", "Genuine alligator leather strap", "Automatic movement, 42hr power reserve", "Sapphire crystal glass", "100m water resistance", "Serial numbered — limited to 200 pieces"],
    care: "Avoid contact with chemicals. Service every 3-5 years. Store in watch box."
  },
  {
    id: 5,
    name: "Heritage Leather Duffle Bag",
    subtitle: "Full-Grain Vegetable-Tanned Leather",
    category: "accessories",
    price: 245000,
    originalPrice: 280000,
    image: "assets/bag.jpg",
    badge: "Staff Pick",
    badgeType: "tag-gold",
    isNew: false,
    colors: ["#8B4513", "#1A1A1A", "#C4A882"],
    colorNames: ["Cognac", "Black", "Sand"],
    sizes: ["One Size"],
    rating: 4.9,
    reviews: 34,
    description: "A timeless weekend duffle crafted from full-grain vegetable-tanned leather. Features solid brass hardware, detachable shoulder strap, and an interior canvas lining. Designed to develop a beautiful patina over time.",
    details: ["Full-grain vegetable-tanned Italian leather", "Solid brass hardware & zippers", "Detachable leather shoulder strap", "Interior canvas lining with zip pocket", "Reinforced bottom", "Dimensions: 50 × 28 × 26 cm"],
    care: "Apply leather conditioner every 3-6 months. Avoid prolonged sun exposure."
  },
  {
    id: 6,
    name: "Pleated Wool Dress Trousers",
    subtitle: "Super 120s Italian Wool",
    category: "wears",
    price: 95000,
    originalPrice: null,
    image: "assets/trousers.jpg",
    badge: null,
    badgeType: null,
    isNew: true,
    colors: ["#2C2C3A", "#1A1A1A", "#4A4A4A"],
    colorNames: ["Charcoal", "Black", "Slate"],
    sizes: ["28", "30", "32", "34", "36"],
    rating: 4.6,
    reviews: 31,
    description: "Elegantly pleated dress trousers in Super 120s Italian wool. High-rise waist with a tapered leg creates a refined, elongated silhouette. Perfect paired with our blazers or worn casually.",
    details: ["Super 120s Italian merino wool", "High-rise with double front pleats", "Tapered leg", "Side pockets, single back welt pocket", "Half-lined to the knee", "Dry clean recommended"],
    care: "Dry clean for best results. Press with steam on wool setting."
  },
  {
    id: 7,
    name: "Tortoiseshell Aviator Sunglasses",
    subtitle: "UV400 Protection, Acetate Frame",
    category: "accessories",
    price: 65000,
    originalPrice: 78000,
    image: "assets/sunglasses.jpg",
    badge: null,
    badgeType: null,
    isNew: false,
    colors: ["#8B4513", "#1A1A1A"],
    colorNames: ["Tortoiseshell", "Gloss Black"],
    sizes: ["One Size"],
    rating: 4.5,
    reviews: 56,
    description: "Classic aviator sunglasses in premium hand-polished acetate with UV400 polarized lenses. Lightweight yet durable with spring hinges for a comfortable fit on any face shape.",
    details: ["Hand-polished Italian acetate frame", "UV400 polarized CR-39 lenses", "Stainless steel spring hinges", "Comes with leather case & microfiber cloth", "Lens width: 56mm", "Bridge: 18mm, Temple: 145mm"],
    care: "Clean with microfiber cloth. Store in included protective case."
  },
  {
    id: 8,
    name: "Italian Suede Chelsea Boots",
    subtitle: "Blake-Stitched Construction",
    category: "footwear",
    price: 155000,
    originalPrice: null,
    image: "assets/boots.jpg",
    badge: "New",
    badgeType: "tag-gold",
    isNew: true,
    colors: ["#A0522D", "#1A1A1A", "#3C3C3C"],
    colorNames: ["Tobacco Suede", "Black Leather", "Dark Grey"],
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    rating: 4.8,
    reviews: 28,
    description: "Premium Chelsea boots in Italian suede with Blake-stitched construction for a sleek, refined profile. Features elastic side panels, pull tab, and a Goodyear-welted leather sole built for durability.",
    details: ["Italian calf suede upper", "Blake-stitched construction", "Leather sole with rubber heel cap", "Elastic side gussets", "Pull loop at heel", "Cushioned leather insole"],
    care: "Apply suede protector spray. Brush regularly with suede brush. Store with shoe trees."
  }
];

const PHONE = "2348000000000";

function formatPrice(n){return "₦" + n.toLocaleString("en-NG")}
